### PR TITLE
Cache ActiveRecord types so that `descendants` is not called once and again

### PR DESCRIPTION
**Pull request by frsantos**
In a Rails 4.2.5 project that I'm developing, I noticed that the profile edit page is very slow, and profiling it with  rack-mini-profiler I can see that much of the time is spent in `Class.descendants`, that is called from `JsonbAccessor::TypeHelper.value_descendants`

For example, my Profile model has 25 attributes, some of them hashes, summing a total of 36 json types. Calling the `descendants` method for each type in a Rails console takes a full 450ms!!:

```ruby
$ rails c
[1] pry(main)> Benchmark.bm {|x| x.report { 36.times {ActiveRecord::Type::Value.descendants} } }
    user     system      total        real
0.450000   0.000000   0.450000 (  0.450793)
```

The project is still in its early stages and there is still only a few classes defined, so when the project grows, I expect this time to grow even more because of the way `.descendants` is implemented.

This PR caches the available types, calling `.descendants` only once. Also, the cached structure is a `Hash` indexed by jsonb type, avoiding the search in an array.

### CODE REVIEW

**Comment by frsantos** [comment]
Actually, I don't know how to test a performance change, apart from checking that all other tests pass. How do you suggest to test it?

**Comment by jhirn** [comment]
I was looking more for ensuring the count of newly created objects and ensuring side effects aren't occurring. I will take a stab at getting some tests around it to get this PR in. Thanks for your contribution.

**Comment by haruska** [comment]
Comparing this while running #15, it's actually a little slower than what's in master when calling Obj.all.to_a

It seems that either/or
1. ActiveRecord::Type::Value.descendants isn't called frequently once the object is defined
2. there is another aspect of initialization that is the real culprit.

**Comment by haruska** [comment]
The performance test from #44 is in master. Feel free to rebase, adjust the test, and run it. If there is another performance test we should consider for this pull request, please add it. Otherwise, this PR should be closed.

**Comment by haruska** [comment]
Closing this for now. Feel free to re-open with a performance test showing improvement.

**Comment by blizkreeg** [comment]
@haruska any chance of re-opening this PR? i love this gem and have used it in a past project, but object instantiation was just much slower than without and eventually had to stop using. 

It's been two years since my comment on https://github.com/devmynd/jsonb_accessor/issues/15 and I want to use the gem again, but I'm not sure if the performance issues have been fixed since. Was a performance test suite ever added to master?

**Comment by blizkreeg** [comment]
@frsantos would you like to re-test this with the performance suite in https://github.com/devmynd/jsonb_accessor/pull/44 and re-submit results?

**Comment by frsantos** [comment]
I'm sorry @blizkreeg, but I no longer work on any project that uses this gem.

**Pull request closed without merging**
